version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    # env_file: backend/.env
    environment:
      - NODE_ENV=development
      - AUTH_JWT_SECRET=7da221c2fe3e186dd1d5368e246cdfff
      - AUTH_JWT_EXPIRES_IN=86400000
      - ORM_TYPE=postgres
      - ORM_HOST=postgres-docker
      - ORM_PORT=5432
      - ORM_USERNAME=postgres
      - ORM_PASSWORD=p0stgr3s
      - ORM_DATABASE=gofinances
    ports:
      - "3333:3333"
    external_links:
      - "postgres:postgres-docker"
    depends_on:
      - postgres

  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgr3s
      POSTGRES_DB: finances
    ports:
      - "5432:5432"
    # volumes:
    #   - /home/samuelfalico/volumes/postgres:/var/lib/postgresql/data

  migration:
    image: finances_backend:latest
    command: ["./wait-for-it/wait-for-it.sh", "postgres-docker:5432", "--", "yarn", "typeorm", "migration:run"]
    external_links:
      - "postgres:postgres-docker"
    depends_on:
      - postgres
      - backend

networks:
  default:
    driver: bridge